### ISSUE TITLE
scene_switch function does not grab the correct scene

### ISSUE THREAD

**Issue by TroikaTronix** [CarloCattano/ObSC#1]
I am a bit confused by the implementation of scene_switch -- shouldn't it be using "filter" parameter as an index to the Scenes array? Right now you can only get scenes 0 and 1. 

See an fixed version on the forum for my software Isadora.

https://community.troikatronix.com/topic/6570/

It uses the filter parameter (now renamed to oscValue) as an index into the scenes array. It also allows this value to be an integer or a float or a string -- as long as it can successfully be converted to an integer. (See the **is_integer** function.)

Best Wishes,
Mark

**Comment by danielfaulknor** [comment]
@TroikaTronix dropping your script in results in an error:

```root@ShowControl:~# python3 Obsc.py
INFO:obswebsocket.core:Connecting...
INFO:obswebsocket.core:Connected!
Traceback (most recent call last):
  File "Obsc.py", line 44, in <module>
    if name == "main":
NameError: name 'name' is not defined
```

**Comment by CarloCattano** [comment]
That's completely right @TroikaTronix for the use you intend. In this case tho is just a demostration of switching between 2 scenes to use along side the max patch, hence the < 60, > 59 to use directly with the values provided by the dial sent over osc.
There is an amazing fork of this project way better than what I demostrated in this demo that I suggest you to look at
Cheers

**Comment by CarloCattano** [comment]
Closing this issue for now
